services:
  postgres:
    container_name: postgres
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - courier-net
    volumes:
      - pg_data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  courier-net:
    driver: bridge

volumes:
  pg_data: