// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package users

import (
	"context"
)

type Querier interface {
	GetByID(ctx context.Context, id int64) (User, error)
	List(ctx context.Context, arg ListParams) ([]User, error)
}

var _ Querier = (*Queries)(nil)
