// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: query.sql

package users

import (
	"context"
)

const getByID = `-- name: GetByID :one
select id, tg_id, full_name, email, phone, role, on_work, verified, rating, balance, created_at, updated_at, password_hash
from users
where id = $1
`

func (q *Queries) GetByID(ctx context.Context, id int64) (*User, error) {
	row := q.db.QueryRowContext(ctx, getByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TgID,
		&i.FullName,
		&i.Email,
		&i.Phone,
		&i.Role,
		&i.OnWork,
		&i.Verified,
		&i.Rating,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
	)
	return &i, err
}

const list = `-- name: List :many
select id, tg_id, full_name, email, phone, role, on_work, verified, rating, balance, created_at, updated_at, password_hash
from users
limit $1
offset $2
`

type ListParams struct {
	Limit  int32 `db:"limit"`
	Offset int32 `db:"offset"`
}

func (q *Queries) List(ctx context.Context, arg ListParams) ([]*User, error) {
	rows, err := q.db.QueryContext(ctx, list, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.TgID,
			&i.FullName,
			&i.Email,
			&i.Phone,
			&i.Role,
			&i.OnWork,
			&i.Verified,
			&i.Rating,
			&i.Balance,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PasswordHash,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
