// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package organizations

import (
	"context"
)

type Querier interface {
	GetByID(ctx context.Context, id int64) (*Organization, error)
}

var _ Querier = (*Queries)(nil)
