// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package organizations_branches

import (
	"database/sql"
	"time"
)

type OrganizationBranch struct {
	ID             int64          `db:"id"`
	OrganizationID int64          `db:"organization_id"`
	Name           string         `db:"name"`
	Address        string         `db:"address"`
	Latitude       sql.NullString `db:"latitude"`
	Longitude      sql.NullString `db:"longitude"`
	Phone          []string       `db:"phone"`
	IsActive       bool           `db:"is_active"`
	CreatedAt      time.Time      `db:"created_at"`
	UpdatedAt      time.Time      `db:"updated_at"`
}
