// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package organizations_branches

import (
	"context"
)

type Querier interface {
	Create(ctx context.Context, arg CreateParams) error
	GetByID(ctx context.Context, arg GetByIDParams) (*OrganizationBranch, error)
	GetByName(ctx context.Context, arg GetByNameParams) (*OrganizationBranch, error)
	List(ctx context.Context, organizationID int64) ([]*OrganizationBranch, error)
}

var _ Querier = (*Queries)(nil)
