// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: query.sql

package organizations_branches

import (
	"context"
	"database/sql"

	"github.com/lib/pq"
)

const create = `-- name: Create :exec
insert into organization_branches(organization_id, name, address, latitude, longitude, phone)
values($1, $2, $3, $4, $5, $6)
`

type CreateParams struct {
	OrganizationID int64          `db:"organization_id"`
	Name           string         `db:"name"`
	Address        string         `db:"address"`
	Latitude       sql.NullString `db:"latitude"`
	Longitude      sql.NullString `db:"longitude"`
	Phone          []string       `db:"phone"`
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) error {
	_, err := q.db.ExecContext(ctx, create,
		arg.OrganizationID,
		arg.Name,
		arg.Address,
		arg.Latitude,
		arg.Longitude,
		pq.Array(arg.Phone),
	)
	return err
}

const getByID = `-- name: GetByID :one
select id, organization_id, name, address, latitude, longitude, phone, is_active, created_at, updated_at
from organization_branches
where organization_id = $1 and id = $2
`

type GetByIDParams struct {
	OrganizationID int64 `db:"organization_id"`
	ID             int64 `db:"id"`
}

func (q *Queries) GetByID(ctx context.Context, arg GetByIDParams) (*OrganizationBranch, error) {
	row := q.db.QueryRowContext(ctx, getByID, arg.OrganizationID, arg.ID)
	var i OrganizationBranch
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Address,
		&i.Latitude,
		&i.Longitude,
		pq.Array(&i.Phone),
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getByName = `-- name: GetByName :one
select id, organization_id, name, address, latitude, longitude, phone, is_active, created_at, updated_at
from organization_branches
where organization_id = $1 and name = $2
`

type GetByNameParams struct {
	OrganizationID int64  `db:"organization_id"`
	Name           string `db:"name"`
}

func (q *Queries) GetByName(ctx context.Context, arg GetByNameParams) (*OrganizationBranch, error) {
	row := q.db.QueryRowContext(ctx, getByName, arg.OrganizationID, arg.Name)
	var i OrganizationBranch
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Address,
		&i.Latitude,
		&i.Longitude,
		pq.Array(&i.Phone),
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const list = `-- name: List :many
select id, organization_id, name, address, latitude, longitude, phone, is_active, created_at, updated_at
from organization_branches
where organization_id = $1
`

func (q *Queries) List(ctx context.Context, organizationID int64) ([]*OrganizationBranch, error) {
	rows, err := q.db.QueryContext(ctx, list, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*OrganizationBranch
	for rows.Next() {
		var i OrganizationBranch
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Address,
			&i.Latitude,
			&i.Longitude,
			pq.Array(&i.Phone),
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
