// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package auth

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Auth struct {
	ID        uuid.UUID    `db:"id"`
	UserID    int64        `db:"user_id"`
	Token     string       `db:"token"`
	ExpiresAt time.Time    `db:"expires_at"`
	CreatedAt sql.NullTime `db:"created_at"`
	RevokedAt sql.NullTime `db:"revoked_at"`
}
