// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: query.sql

package auth

import (
	"context"
	"database/sql"
	"time"
)

const getActiveRefreshToken = `-- name: GetActiveRefreshToken :one
SELECT id, user_id, token, expires_at, created_at, revoked_at FROM auth
WHERE token = $1
  AND revoked_at IS NULL
  AND expires_at > NOW()
`

func (q *Queries) GetActiveRefreshToken(ctx context.Context, token string) (*Auth, error) {
	row := q.db.QueryRowContext(ctx, getActiveRefreshToken, token)
	var i Auth
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return &i, err
}

const logout = `-- name: Logout :exec
update auth
set revoked_at = $1
where user_id = $2
`

type LogoutParams struct {
	RevokedAt sql.NullTime `db:"revoked_at"`
	UserID    int64        `db:"user_id"`
}

func (q *Queries) Logout(ctx context.Context, arg LogoutParams) error {
	_, err := q.db.ExecContext(ctx, logout, arg.RevokedAt, arg.UserID)
	return err
}

const revokeToken = `-- name: RevokeToken :exec
UPDATE auth
SET revoked_at = CURRENT_TIMESTAMP
WHERE token = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeToken(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, revokeToken, token)
	return err
}

const save = `-- name: Save :exec
insert into auth (user_id, token, expires_at, revoked_at)
values ($3, $1, $2, NULL)
on conflict (user_id) do update
set
    token = EXCLUDED.token,
    expires_at = EXCLUDED.expires_at,
    revoked_at = NULL
`

type SaveParams struct {
	Token     string    `db:"token"`
	ExpiresAt time.Time `db:"expires_at"`
	UserID    int64     `db:"user_id"`
}

func (q *Queries) Save(ctx context.Context, arg SaveParams) error {
	_, err := q.db.ExecContext(ctx, save, arg.Token, arg.ExpiresAt, arg.UserID)
	return err
}
