// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package auth

import (
	"context"
)

type Querier interface {
	GetActiveRefreshToken(ctx context.Context, token string) (*Auth, error)
	Logout(ctx context.Context, arg LogoutParams) error
	RevokeToken(ctx context.Context, token string) error
	Save(ctx context.Context, arg SaveParams) error
}

var _ Querier = (*Queries)(nil)
