// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: query.sql

package orders

import (
	"context"
	"database/sql"
	"time"
)

const createOrder = `-- name: CreateOrder :one
insert into orders(organization_id, from_address, from_lat, from_lon, to_address, to_lat, to_lon, description)
values($1, $2, $3, $4, $5, $6, $7, $8)
returning id
`

type CreateOrderParams struct {
	OrganizationID int64          `db:"organization_id"`
	FromAddress    string         `db:"from_address"`
	FromLat        string         `db:"from_lat"`
	FromLon        string         `db:"from_lon"`
	ToAddress      string         `db:"to_address"`
	ToLat          string         `db:"to_lat"`
	ToLon          string         `db:"to_lon"`
	Description    sql.NullString `db:"description"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createOrder,
		arg.OrganizationID,
		arg.FromAddress,
		arg.FromLat,
		arg.FromLon,
		arg.ToAddress,
		arg.ToLat,
		arg.ToLon,
		arg.Description,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getAll = `-- name: GetAll :many
select id, description, organization_id, courier_id, status, from_address, from_lat, from_lon, to_address, to_lat, to_lon, tg_client_chat_id, tg_live_message_id, created_at, updated_at, branch_id, courier_earnings, delivery_distance_meters, tg_courier_chat_id, accepted_at, picked_up_at, delivered_at, cancelled_at
from orders
where organization_id = $1
offset $2
limit $3
`

type GetAllParams struct {
	OrganizationID int64 `db:"organization_id"`
	Offset         int32 `db:"offset"`
	Limit          int32 `db:"limit"`
}

func (q *Queries) GetAll(ctx context.Context, arg GetAllParams) ([]*Order, error) {
	rows, err := q.db.QueryContext(ctx, getAll, arg.OrganizationID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.OrganizationID,
			&i.CourierID,
			&i.Status,
			&i.FromAddress,
			&i.FromLat,
			&i.FromLon,
			&i.ToAddress,
			&i.ToLat,
			&i.ToLon,
			&i.TgClientChatID,
			&i.TgLiveMessageID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BranchID,
			&i.CourierEarnings,
			&i.DeliveryDistanceMeters,
			&i.TgCourierChatID,
			&i.AcceptedAt,
			&i.PickedUpAt,
			&i.DeliveredAt,
			&i.CancelledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getByID = `-- name: GetByID :one
select id, description, organization_id, courier_id, status, from_address, from_lat, from_lon, to_address, to_lat, to_lon, tg_client_chat_id, tg_live_message_id, created_at, updated_at, branch_id, courier_earnings, delivery_distance_meters, tg_courier_chat_id, accepted_at, picked_up_at, delivered_at, cancelled_at
from orders
where id = $1 and organization_id = $2
`

type GetByIDParams struct {
	ID             int64 `db:"id"`
	OrganizationID int64 `db:"organization_id"`
}

func (q *Queries) GetByID(ctx context.Context, arg GetByIDParams) (*Order, error) {
	row := q.db.QueryRowContext(ctx, getByID, arg.ID, arg.OrganizationID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.OrganizationID,
		&i.CourierID,
		&i.Status,
		&i.FromAddress,
		&i.FromLat,
		&i.FromLon,
		&i.ToAddress,
		&i.ToLat,
		&i.ToLon,
		&i.TgClientChatID,
		&i.TgLiveMessageID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BranchID,
		&i.CourierEarnings,
		&i.DeliveryDistanceMeters,
		&i.TgCourierChatID,
		&i.AcceptedAt,
		&i.PickedUpAt,
		&i.DeliveredAt,
		&i.CancelledAt,
	)
	return &i, err
}

const updateCourier = `-- name: UpdateCourier :exec
update orders
set courier_id = $1, tg_client_chat_id = $2, tg_live_message_id = $3, updated_at = $4
where id = $5
`

type UpdateCourierParams struct {
	CourierID       sql.NullInt64 `db:"courier_id"`
	TgClientChatID  sql.NullInt64 `db:"tg_client_chat_id"`
	TgLiveMessageID sql.NullInt64 `db:"tg_live_message_id"`
	UpdatedAt       time.Time     `db:"updated_at"`
	ID              int64         `db:"id"`
}

func (q *Queries) UpdateCourier(ctx context.Context, arg UpdateCourierParams) error {
	_, err := q.db.ExecContext(ctx, updateCourier,
		arg.CourierID,
		arg.TgClientChatID,
		arg.TgLiveMessageID,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
