// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package orders

import (
	"context"
)

type Querier interface {
	CancelOrder(ctx context.Context, arg CancelOrderParams) error
	CreateOrder(ctx context.Context, arg CreateOrderParams) (int64, error)
	GetAll(ctx context.Context, arg GetAllParams) ([]*Order, error)
	GetByID(ctx context.Context, arg GetByIDParams) (*Order, error)
	UpdateCourier(ctx context.Context, arg UpdateCourierParams) error
}

var _ Querier = (*Queries)(nil)
