// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package orders

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"
)

type OrderStatus string

const (
	OrderStatusCreated   OrderStatus = "created"
	OrderStatusAccepted  OrderStatus = "accepted"
	OrderStatusPickedUp  OrderStatus = "picked_up"
	OrderStatusDelivered OrderStatus = "delivered"
	OrderStatusCancelled OrderStatus = "cancelled"
)

func (e *OrderStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrderStatus(s)
	case string:
		*e = OrderStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OrderStatus: %T", src)
	}
	return nil
}

type NullOrderStatus struct {
	OrderStatus OrderStatus
	Valid       bool // Valid is true if OrderStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrderStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OrderStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrderStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrderStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrderStatus), nil
}

type Order struct {
	ID                     int64          `db:"id"`
	Description            sql.NullString `db:"description"`
	OrganizationID         int64          `db:"organization_id"`
	CourierID              sql.NullInt64  `db:"courier_id"`
	Status                 OrderStatus    `db:"status"`
	FromAddress            string         `db:"from_address"`
	FromLat                string         `db:"from_lat"`
	FromLon                string         `db:"from_lon"`
	ToAddress              string         `db:"to_address"`
	ToLat                  string         `db:"to_lat"`
	ToLon                  string         `db:"to_lon"`
	TgClientChatID         sql.NullInt64  `db:"tg_client_chat_id"`
	TgLiveMessageID        sql.NullInt64  `db:"tg_live_message_id"`
	CreatedAt              time.Time      `db:"created_at"`
	UpdatedAt              time.Time      `db:"updated_at"`
	BranchID               sql.NullInt64  `db:"branch_id"`
	CourierEarnings        string         `db:"courier_earnings"`
	DeliveryDistanceMeters int32          `db:"delivery_distance_meters"`
	TgCourierChatID        sql.NullInt64  `db:"tg_courier_chat_id"`
	AcceptedAt             sql.NullTime   `db:"accepted_at"`
	PickedUpAt             sql.NullTime   `db:"picked_up_at"`
	DeliveredAt            sql.NullTime   `db:"delivered_at"`
	CancelledAt            sql.NullTime   `db:"cancelled_at"`
}
