// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package orders

import (
	"context"
)

type Querier interface {
	GetByID(ctx context.Context, id int64) (*Order, error)
	GetPendingOrders(ctx context.Context) ([]*Order, error)
}

var _ Querier = (*Queries)(nil)
