// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: query.sql

package orders

import (
	"context"
)

const getByID = `-- name: GetByID :one
select id, description, organization_id, courier_id, status, from_address, from_lat, from_lon, to_address, to_lat, to_lon, tg_client_chat_id, tg_live_message_id, created_at, updated_at, branch_id, courier_earnings, delivery_distance_meters, tg_courier_chat_id, accepted_at, picked_up_at, delivered_at, cancelled_at
from orders
where id = $1
`

func (q *Queries) GetByID(ctx context.Context, id int64) (*Order, error) {
	row := q.db.QueryRowContext(ctx, getByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.OrganizationID,
		&i.CourierID,
		&i.Status,
		&i.FromAddress,
		&i.FromLat,
		&i.FromLon,
		&i.ToAddress,
		&i.ToLat,
		&i.ToLon,
		&i.TgClientChatID,
		&i.TgLiveMessageID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BranchID,
		&i.CourierEarnings,
		&i.DeliveryDistanceMeters,
		&i.TgCourierChatID,
		&i.AcceptedAt,
		&i.PickedUpAt,
		&i.DeliveredAt,
		&i.CancelledAt,
	)
	return &i, err
}

const getPendingOrders = `-- name: GetPendingOrders :many
select id, description, organization_id, courier_id, status, from_address, from_lat, from_lon, to_address, to_lat, to_lon, tg_client_chat_id, tg_live_message_id, created_at, updated_at, branch_id, courier_earnings, delivery_distance_meters, tg_courier_chat_id, accepted_at, picked_up_at, delivered_at, cancelled_at
from orders
where status = 'created'
`

func (q *Queries) GetPendingOrders(ctx context.Context) ([]*Order, error) {
	rows, err := q.db.QueryContext(ctx, getPendingOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.OrganizationID,
			&i.CourierID,
			&i.Status,
			&i.FromAddress,
			&i.FromLat,
			&i.FromLon,
			&i.ToAddress,
			&i.ToLat,
			&i.ToLon,
			&i.TgClientChatID,
			&i.TgLiveMessageID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BranchID,
			&i.CourierEarnings,
			&i.DeliveryDistanceMeters,
			&i.TgCourierChatID,
			&i.AcceptedAt,
			&i.PickedUpAt,
			&i.DeliveredAt,
			&i.CancelledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
