// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: query.sql

package orders

import (
	"context"
	"database/sql"
)

const acceptOrder = `-- name: AcceptOrder :exec
update orders
set courier_id = $1, status = $2, tg_courier_chat_id = $3, accepted_at = now()
where id = $4
`

type AcceptOrderParams struct {
	CourierID       sql.NullInt64 `db:"courier_id"`
	Status          OrderStatus   `db:"status"`
	TgCourierChatID sql.NullInt64 `db:"tg_courier_chat_id"`
	ID              int64         `db:"id"`
}

func (q *Queries) AcceptOrder(ctx context.Context, arg AcceptOrderParams) error {
	_, err := q.db.ExecContext(ctx, acceptOrder,
		arg.CourierID,
		arg.Status,
		arg.TgCourierChatID,
		arg.ID,
	)
	return err
}

const doneOrder = `-- name: DoneOrder :exec
update orders
set status = 'delivered', delivered_at = now()
where id = $1
`

func (q *Queries) DoneOrder(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, doneOrder, id)
	return err
}

const getByID = `-- name: GetByID :one
select id, description, organization_id, status, from_address, from_lat, from_lon, to_address, to_lat, to_lon, created_at, updated_at, branch_id, courier_earnings, delivery_distance_meters, tg_courier_chat_id, accepted_at, picked_up_at, delivered_at, cancelled_at, courier_id, price
from orders
where id = $1
`

func (q *Queries) GetByID(ctx context.Context, id int64) (*Order, error) {
	row := q.db.QueryRowContext(ctx, getByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.OrganizationID,
		&i.Status,
		&i.FromAddress,
		&i.FromLat,
		&i.FromLon,
		&i.ToAddress,
		&i.ToLat,
		&i.ToLon,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BranchID,
		&i.CourierEarnings,
		&i.DeliveryDistanceMeters,
		&i.TgCourierChatID,
		&i.AcceptedAt,
		&i.PickedUpAt,
		&i.DeliveredAt,
		&i.CancelledAt,
		&i.CourierID,
		&i.Price,
	)
	return &i, err
}

const getCourierActiveOrder = `-- name: GetCourierActiveOrder :one
select id, description, organization_id, status, from_address, from_lat, from_lon, to_address, to_lat, to_lon, created_at, updated_at, branch_id, courier_earnings, delivery_distance_meters, tg_courier_chat_id, accepted_at, picked_up_at, delivered_at, cancelled_at, courier_id, price
from orders
where courier_id = $1 and status not in ('created','delivered','cancelled')
limit 1
`

func (q *Queries) GetCourierActiveOrder(ctx context.Context, courierID sql.NullInt64) (*Order, error) {
	row := q.db.QueryRowContext(ctx, getCourierActiveOrder, courierID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.OrganizationID,
		&i.Status,
		&i.FromAddress,
		&i.FromLat,
		&i.FromLon,
		&i.ToAddress,
		&i.ToLat,
		&i.ToLon,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BranchID,
		&i.CourierEarnings,
		&i.DeliveryDistanceMeters,
		&i.TgCourierChatID,
		&i.AcceptedAt,
		&i.PickedUpAt,
		&i.DeliveredAt,
		&i.CancelledAt,
		&i.CourierID,
		&i.Price,
	)
	return &i, err
}

const getPendingOrders = `-- name: GetPendingOrders :many
select id, description, organization_id, status, from_address, from_lat, from_lon, to_address, to_lat, to_lon, created_at, updated_at, branch_id, courier_earnings, delivery_distance_meters, tg_courier_chat_id, accepted_at, picked_up_at, delivered_at, cancelled_at, courier_id, price
from orders
where status = 'created'
`

func (q *Queries) GetPendingOrders(ctx context.Context) ([]*Order, error) {
	rows, err := q.db.QueryContext(ctx, getPendingOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.OrganizationID,
			&i.Status,
			&i.FromAddress,
			&i.FromLat,
			&i.FromLon,
			&i.ToAddress,
			&i.ToLat,
			&i.ToLon,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BranchID,
			&i.CourierEarnings,
			&i.DeliveryDistanceMeters,
			&i.TgCourierChatID,
			&i.AcceptedAt,
			&i.PickedUpAt,
			&i.DeliveredAt,
			&i.CancelledAt,
			&i.CourierID,
			&i.Price,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pickUpOrder = `-- name: PickUpOrder :exec
update orders
set status = 'picked_up', picked_up_at = now()
where id = $1
`

func (q *Queries) PickUpOrder(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, pickUpOrder, id)
	return err
}
