// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package orders

import (
	"context"
	"database/sql"
)

type Querier interface {
	AcceptOrder(ctx context.Context, arg AcceptOrderParams) error
	DoneOrder(ctx context.Context, id int64) error
	GetByID(ctx context.Context, id int64) (*Order, error)
	GetCourierActiveOrder(ctx context.Context, courierID sql.NullInt64) (*Order, error)
	GetPendingOrders(ctx context.Context) ([]*Order, error)
	PickUpOrder(ctx context.Context, id int64) error
}

var _ Querier = (*Queries)(nil)
