services:
  backend:
    container_name: backend
    build:
      context: deploy/backend
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: always
    expose:
      - 80
      - 443
      - 8080
    networks:
      - postgres_courier-net
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  postgres_courier-net:
    external: true