// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package organizations

import (
	"database/sql"
	"time"
)

type Organization struct {
	ID        int64          `db:"id"`
	Name      string         `db:"name"`
	Inn       sql.NullString `db:"inn"`
	Balance   string         `db:"balance"`
	IsActive  bool           `db:"is_active"`
	Verified  bool           `db:"verified"`
	CreatedAt time.Time      `db:"created_at"`
	UpdatedAt time.Time      `db:"updated_at"`
}
