// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: query.sql

package organizations

import (
	"context"
)

const getByID = `-- name: GetByID :one
select id, name, inn, balance, is_active, verified, created_at, updated_at
from organizations
where id = $1
`

func (q *Queries) GetByID(ctx context.Context, id int64) (*Organization, error) {
	row := q.db.QueryRowContext(ctx, getByID, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Inn,
		&i.Balance,
		&i.IsActive,
		&i.Verified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const payOrder = `-- name: PayOrder :exec
update organizations
set balance = $1
where id = $2
`

type PayOrderParams struct {
	Balance string `db:"balance"`
	ID      int64  `db:"id"`
}

func (q *Queries) PayOrder(ctx context.Context, arg PayOrderParams) error {
	_, err := q.db.ExecContext(ctx, payOrder, arg.Balance, arg.ID)
	return err
}
