// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: query.sql

package users

import (
	"context"
	"database/sql"
)

const createByEmail = `-- name: CreateByEmail :exec
insert into users(email, role, password_hash, full_name)
values($1, $2, $3, $4)
`

type CreateByEmailParams struct {
	Email        sql.NullString `db:"email"`
	Role         RoleType       `db:"role"`
	PasswordHash sql.NullString `db:"password_hash"`
	FullName     sql.NullString `db:"full_name"`
}

func (q *Queries) CreateByEmail(ctx context.Context, arg CreateByEmailParams) error {
	_, err := q.db.ExecContext(ctx, createByEmail,
		arg.Email,
		arg.Role,
		arg.PasswordHash,
		arg.FullName,
	)
	return err
}

const getByEmail = `-- name: GetByEmail :one
select id, tg_id, full_name, email, phone, role, on_work, verified, rating, balance, created_at, updated_at, password_hash, organization_id, is_share_location, share_location_ttl
from users
where email = $1
`

func (q *Queries) GetByEmail(ctx context.Context, email sql.NullString) (*User, error) {
	row := q.db.QueryRowContext(ctx, getByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TgID,
		&i.FullName,
		&i.Email,
		&i.Phone,
		&i.Role,
		&i.OnWork,
		&i.Verified,
		&i.Rating,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
		&i.OrganizationID,
		&i.IsShareLocation,
		&i.ShareLocationTtl,
	)
	return &i, err
}

const getByID = `-- name: GetByID :one
select id, tg_id, full_name, email, phone, role, on_work, verified, rating, balance, created_at, updated_at, password_hash, organization_id, is_share_location, share_location_ttl
from users
where id = $1
`

func (q *Queries) GetByID(ctx context.Context, id int64) (*User, error) {
	row := q.db.QueryRowContext(ctx, getByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TgID,
		&i.FullName,
		&i.Email,
		&i.Phone,
		&i.Role,
		&i.OnWork,
		&i.Verified,
		&i.Rating,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
		&i.OrganizationID,
		&i.IsShareLocation,
		&i.ShareLocationTtl,
	)
	return &i, err
}
