// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package users

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateByEmail(ctx context.Context, arg CreateByEmailParams) error
	GetByEmail(ctx context.Context, email sql.NullString) (*User, error)
	GetByID(ctx context.Context, id int64) (*User, error)
}

var _ Querier = (*Queries)(nil)
