// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package users

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"
)

type RoleType string

const (
	RoleTypeCourier RoleType = "courier"
	RoleTypeClient  RoleType = "client"
	RoleTypeAdmin   RoleType = "admin"
)

func (e *RoleType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RoleType(s)
	case string:
		*e = RoleType(s)
	default:
		return fmt.Errorf("unsupported scan type for RoleType: %T", src)
	}
	return nil
}

type NullRoleType struct {
	RoleType RoleType
	Valid    bool // Valid is true if RoleType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRoleType) Scan(value interface{}) error {
	if value == nil {
		ns.RoleType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RoleType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRoleType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RoleType), nil
}

type User struct {
	ID             int64          `db:"id"`
	TgID           sql.NullInt64  `db:"tg_id"`
	FullName       sql.NullString `db:"full_name"`
	Email          sql.NullString `db:"email"`
	Phone          sql.NullString `db:"phone"`
	Role           RoleType       `db:"role"`
	OnWork         bool           `db:"on_work"`
	Verified       bool           `db:"verified"`
	Rating         sql.NullString `db:"rating"`
	Balance        sql.NullString `db:"balance"`
	CreatedAt      time.Time      `db:"created_at"`
	UpdatedAt      time.Time      `db:"updated_at"`
	PasswordHash   sql.NullString `db:"password_hash"`
	OrganizationID sql.NullInt64  `db:"organization_id"`
}
