// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: query.sql

package users

import (
	"context"
	"database/sql"
)

const create = `-- name: Create :one
insert into users(tg_id, full_name, email, phone, role)
values($1, $2, $3, $4, $5)
returning id
`

type CreateParams struct {
	TgID     sql.NullInt64  `db:"tg_id"`
	FullName sql.NullString `db:"full_name"`
	Email    sql.NullString `db:"email"`
	Phone    sql.NullString `db:"phone"`
	Role     RoleType       `db:"role"`
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, create,
		arg.TgID,
		arg.FullName,
		arg.Email,
		arg.Phone,
		arg.Role,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const expiredShareLocationList = `-- name: ExpiredShareLocationList :many
select id, tg_id, full_name, email, phone, role, on_work, verified, rating, balance, created_at, updated_at, password_hash, organization_id, is_share_location, share_location_ttl
from users
where share_location_ttl < now()
`

func (q *Queries) ExpiredShareLocationList(ctx context.Context) ([]*User, error) {
	rows, err := q.db.QueryContext(ctx, expiredShareLocationList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.TgID,
			&i.FullName,
			&i.Email,
			&i.Phone,
			&i.Role,
			&i.OnWork,
			&i.Verified,
			&i.Rating,
			&i.Balance,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PasswordHash,
			&i.OrganizationID,
			&i.IsShareLocation,
			&i.ShareLocationTtl,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getByTgID = `-- name: GetByTgID :one
select id, tg_id, full_name, email, phone, role, on_work, verified, rating, balance, created_at, updated_at, password_hash, organization_id, is_share_location, share_location_ttl
from users
where tg_id = $1
`

func (q *Queries) GetByTgID(ctx context.Context, tgID sql.NullInt64) (*User, error) {
	row := q.db.QueryRowContext(ctx, getByTgID, tgID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TgID,
		&i.FullName,
		&i.Email,
		&i.Phone,
		&i.Role,
		&i.OnWork,
		&i.Verified,
		&i.Rating,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
		&i.OrganizationID,
		&i.IsShareLocation,
		&i.ShareLocationTtl,
	)
	return &i, err
}

const setOnWork = `-- name: SetOnWork :exec
update users
set on_work = $1
where tg_id = $2
`

type SetOnWorkParams struct {
	OnWork bool          `db:"on_work"`
	TgID   sql.NullInt64 `db:"tg_id"`
}

func (q *Queries) SetOnWork(ctx context.Context, arg SetOnWorkParams) error {
	_, err := q.db.ExecContext(ctx, setOnWork, arg.OnWork, arg.TgID)
	return err
}

const setShareLocation = `-- name: SetShareLocation :exec
update users
set is_share_location = $1, share_location_ttl = $2, on_work = $3
where tg_id = $4
`

type SetShareLocationParams struct {
	IsShareLocation  bool          `db:"is_share_location"`
	ShareLocationTtl sql.NullTime  `db:"share_location_ttl"`
	OnWork           bool          `db:"on_work"`
	TgID             sql.NullInt64 `db:"tg_id"`
}

func (q *Queries) SetShareLocation(ctx context.Context, arg SetShareLocationParams) error {
	_, err := q.db.ExecContext(ctx, setShareLocation,
		arg.IsShareLocation,
		arg.ShareLocationTtl,
		arg.OnWork,
		arg.TgID,
	)
	return err
}

const updatePhoneByTgID = `-- name: UpdatePhoneByTgID :exec
update users
set phone = $1
where tg_id = $2
`

type UpdatePhoneByTgIDParams struct {
	Phone sql.NullString `db:"phone"`
	TgID  sql.NullInt64  `db:"tg_id"`
}

func (q *Queries) UpdatePhoneByTgID(ctx context.Context, arg UpdatePhoneByTgIDParams) error {
	_, err := q.db.ExecContext(ctx, updatePhoneByTgID, arg.Phone, arg.TgID)
	return err
}
