// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package users

import (
	"context"
)

type Querier interface {
	Create(ctx context.Context, arg CreateParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
