// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package users

import (
	"context"
	"database/sql"
)

type Querier interface {
	Create(ctx context.Context, arg CreateParams) error
	GetByTgID(ctx context.Context, tgID sql.NullInt64) (User, error)
	UpdatePhoneByTgID(ctx context.Context, arg UpdatePhoneByTgIDParams) error
}

var _ Querier = (*Queries)(nil)
