// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: query.sql

package users

import (
	"context"
	"database/sql"
)

const create = `-- name: Create :one
insert into users(tg_id, full_name, email, phone, role)
values($1, $2, $3, $4, $5)
returning id
`

type CreateParams struct {
	TgID     sql.NullInt64  `db:"tg_id"`
	FullName sql.NullString `db:"full_name"`
	Email    sql.NullString `db:"email"`
	Phone    string         `db:"phone"`
	Role     RoleType       `db:"role"`
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, create,
		arg.TgID,
		arg.FullName,
		arg.Email,
		arg.Phone,
		arg.Role,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
