// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package users

import (
	"context"
	"database/sql"
)

type Querier interface {
	Create(ctx context.Context, arg CreateParams) (int64, error)
	ExpiredShareLocationList(ctx context.Context) ([]*User, error)
	GetByTgID(ctx context.Context, tgID sql.NullInt64) (*User, error)
	SetOnWork(ctx context.Context, arg SetOnWorkParams) error
	SetShareLocation(ctx context.Context, arg SetShareLocationParams) error
	UpdatePhoneByTgID(ctx context.Context, arg UpdatePhoneByTgIDParams) error
}

var _ Querier = (*Queries)(nil)
