// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package branch_geozones

import (
	"database/sql"
)

type BranchGeozone struct {
	ID                   int32        `db:"id"`
	OrganizationBranchID int32        `db:"organization_branch_id"`
	Name                 string       `db:"name"`
	Zone                 interface{}  `db:"zone"`
	CreatedAt            sql.NullTime `db:"created_at"`
	UpdatedAt            sql.NullTime `db:"updated_at"`
}
