// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package branch_geozones

import (
	"context"
)

type Querier interface {
	GetByCoords(ctx context.Context, arg GetByCoordsParams) (*GetByCoordsRow, error)
	GetByID(ctx context.Context, id int32) (*BranchGeozone, error)
}

var _ Querier = (*Queries)(nil)
