// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: query.sql

package branch_geozones

import (
	"context"
)

const getByCoords = `-- name: GetByCoords :one
SELECT organization_branch_id, name
FROM branch_geozones
WHERE ST_Contains(
    zone,
    ST_SetSRID(ST_Point($1::numeric, $2::numeric), 4326) -- Передаем (Долгота, Широта)
)
`

type GetByCoordsParams struct {
	Column1 string `db:"column_1"`
	Column2 string `db:"column_2"`
}

type GetByCoordsRow struct {
	OrganizationBranchID int32  `db:"organization_branch_id"`
	Name                 string `db:"name"`
}

func (q *Queries) GetByCoords(ctx context.Context, arg GetByCoordsParams) (*GetByCoordsRow, error) {
	row := q.db.QueryRowContext(ctx, getByCoords, arg.Column1, arg.Column2)
	var i GetByCoordsRow
	err := row.Scan(&i.OrganizationBranchID, &i.Name)
	return &i, err
}

const getByID = `-- name: GetByID :one
select id, organization_branch_id, name, zone, created_at, updated_at
from branch_geozones
where id = $1
`

func (q *Queries) GetByID(ctx context.Context, id int32) (*BranchGeozone, error) {
	row := q.db.QueryRowContext(ctx, getByID, id)
	var i BranchGeozone
	err := row.Scan(
		&i.ID,
		&i.OrganizationBranchID,
		&i.Name,
		&i.Zone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
